version: "3.8"
services:
  app:
    container_name: app-lightning-atm-mainan-ui
    image: nginx
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.fix-prefix.stripprefix.prefixes=/"
      - "traefik.http.middlewares.fix-the-trailing.redirectregex.regex=((?:.*([/][0-9a-z_-]{1,})$$).*$$)"
      - "traefik.http.middlewares.fix-the-trailing.redirectregex.replacement=$${1}/"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.rule=((Host(`roaringstars.com`) || Host(`labs.roaringstars.com`)) && PathPrefix(`/`))"
      - "traefik.http.routers.app-secure.middlewares=fix-prefix,fix-the-trailing"
      - "traefik.http.middlewares.app-ratelimit.ratelimit.average=25"
      - "traefik.http.middlewares.app-ratelimit.ratelimit.burst=15"
    ports:
      - ${APP_HTTPS_PORT}:80
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_PORT=80
    networks:
      - proxy
    restart: always
    mem_limit: 50m

networks:
  proxy:
    external: true