{
"trx_id": "a58ddc68-xxxx-xxxx-xxxx-ad9589d07b6d",
"trx_status": "cancelled",
"idr_amount": 10000,
"satoshi_amount": 0,
"is_refundable": false,
"trx_created_at": 1655655982,
"idr_paid_at": null,
"closing_trx_at": null,
"lnurl_created_at": null,
"lnurl_scan_at": null,
"lnurl_paid_at": null,
"lnurl_pr_data": null,
"lnurl_fee": 0,
"lnurl_ott": null,
"lnurl_status": "notfound",
"lnurl_status_error_message": null,
"pr_amount_valid": false,
"pr_amount": null,
"pr_hash": null,
"pr_pubkey": null,
"pr_payee_node_key": null,
"pr_singnature": null,
"pr_expires": null,
"total_trx_time_sec": 0,
"time_percentage_label": [],
"time_percentage_value": []
}