name: Build Check

on:  
  pull_request:
    branches:
      - main

jobs:
  CD:
    name: CD
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@4.11.1

      - name: Build
        run: npm run build
          

